// This file has been generated by Hyperschema, using Specta. DO NOT EDIT.

import { Transport } from '@hyperschema/client-ts';

export type Animal = { name: string; age: number }

export type Human = { name: string; age: number; pet: Animal | null }

export class MikotoClient {
  readonly humans: HumanService;
  constructor(protected transport: Transport) {
    this.humans = new HumanService(this.transport);
  }
  ping(arg: string): Promise<string> { return this.transport.query('ping', arg); }
}

export class HumanService {
  constructor(protected transport: Transport) {
  }
  derp(arg: null): Promise<null> { return this.transport.query('humans.derp', arg); }
  get(arg: string): Promise<Human> { return this.transport.query('humans.get', arg); }
  set(arg: string): Promise<Human> { return this.transport.procedure('humans.set', arg); }
}

